name: Deploy to Vercel

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build Flutter Web
        run: flutter build web --release

      - name: Generate Service Worker
        run: python generate_sw.py

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        working-directory: build/web
        env:
          VERCEL_ORG_ID: team_elzJTKVd1OK4l8GlZDbJys46
          VERCEL_PROJECT_ID: prj_WJq2LtZRijgYiS1CAr8fkpg18Ypr
        run: vercel pull --yes --environment=production --token=${{ secrets.Vercel_Token_PWA }}

      - name: Build Project Artifacts
        working-directory: build/web
        env:
          VERCEL_ORG_ID: team_elzJTKVd1OK4l8GlZDbJys46
          VERCEL_PROJECT_ID: prj_WJq2LtZRijgYiS1CAr8fkpg18Ypr
        run: vercel build --prod --token=${{ secrets.Vercel_Token_PWA }}

      - name: Deploy Project Artifacts to Vercel
        working-directory: build/web
        env:
          VERCEL_ORG_ID: team_elzJTKVd1OK4l8GlZDbJys46
          VERCEL_PROJECT_ID: prj_WJq2LtZRijgYiS1CAr8fkpg18Ypr
        run: vercel deploy --prebuilt --prod --token=${{ secrets.Vercel_Token_PWA }}
